openapi: 3.0.1
info:
  title: STD21028 API
  description: 'Global description of my API'
  version: 1.0.0
servers:
 - url: https://STD21028.com
tags: 
 - name: Students
 - name: Courses
paths:
 /students:
    get:
      tags:
        - Students
      operationId: getStudents
      summary: Get all students
      description: Get all students with details
      responses:
        200: 
          description: List of students
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Student'
        400:
          description: Bad request
    post: 
      tags:
        - Students
      operationId: createStudent
      summary : Create new student
      description: Create new student
      requestBody:
        description: Student to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateStudent'
        required: true
      responses:
        200:
          description: List of students
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateStudent'
        400:
          description: Bad request 
          
    put: 
      tags:
        - Students 
      operationId: update student
      summary: Update an existing student
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
          application/xml:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        200:
          description: Student updated 
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Student'
        404:
          description: Student not found
          content: {}
    
    patch:
      tags:
        - Students
      summary: Update an existing student
      operationId: Update student
      description: |
        Possible updates on: 
        * name : change
        * address : change
        * birth_date : change
        * phoneNumbers : add 
      requestBody:
        description: STUDENTS 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
            examples:
              changeName:
                summary: Change name
                description: How to change name and what it does
                value:
                  id: 1
                  name: "New name"
              ChangeAddress:
                summary: Change address
                description: How to change address 
                value:
                  id: 1
                  address: "Ivandry"
              ChangeNameAndAddress:
                summary: Change name and address but not all 
                value: 
                  name: "Rakoto"
                  address: "Ivandry"
              addPhoneNumbers:
                summary: Add new phone numbers 
                value:
                  id: 1
                  numbers:
                  - country_code : "+261"
                    number: "0341126005"

          application/xml:
            schema:
              $ref: '#/components/schemas/Student'
        required: true
      responses:
        200: 
          description: Student updated
          content: 
            application/json:
              schema:
                  $ref: '#/components/schemas/Student'
        400:
          description: Invalid ID supplied
          content: {}
        404:
          description: Student not found
          

         
 /student/{id}:
    get:
      tags:
        - Students
      operationId: getStudentId
      summary: Get informations about a specific student
      description: Get informations of a specific student
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            example: 2
          required: true
      responses:
        200:
          description : Details of a student
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
        400:
          description: Bad request
    delete:
      tags:
        - Students
      operationId: deleteStudent
      summary: Delete a student
      description : Delete the student having the entered id
      parameters:
        - name: id
          in : path
          schema:
            type: integer
            example: 2
          required: true
      responses:
        200:
          description: Student deleted successfully
        400:
          description: Bad request
          
   
 /courses:
    get:
      tags:
        - Courses
      operationId: getCourses
      summary: Get all courses
      description: Get all courses with details
      responses:
        200:
          description: List of courses
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Course'
        400:
          description: Bad request
    post:
      tags:
        - Courses
      operationId: CreateCourse
      summary: Create new courses
      description: Create new course
      requestBody:
        description: Course to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourse'
        required: true
      responses:
        200:
          description: List of courses
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        400:
          description: Bad request
    
    put: 
      tags:
        - Courses 
      summary: Update an existing course
      operationId: update course
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCourse'
          application/xml:
            schema:
              $ref: '#/components/schemas/CreateCourse'
        required: true
      responses:
        200: 
          description: Course updated
        404:
          description: Course not found
          content: {}
        
    patch: 
      tags:
        - Courses 
      summary: Update an existing course
      requestBody:
        description: Pet object that needs to be added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Course'
          application/xml:
            schema:
              $ref: '#/components/schemas/Course'
        required: true
      responses:
        200:
          description: Course been updated 
        404:
          description: Student not found
          content: {} 
          
 /courses/{id}:
    get:
      tags:
        - Courses
      operationId: getCourseId
      summary: Get informations about a specific course
      description: Informations about a course
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            example: 2
          required: true
      responses:
        200:
          description: details about a course
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Course'
        400:
          description: Bad request
    delete:
      tags:
        - Courses
      operationId: deleteCourse
      summary: Delete a course
      description: Delete the course having the entered id
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            example: 2
          required: true
      responses:
        200:
          description: Course deleted successfully
        400:
          description: Bad request
          
components:
  schemas:
  
    phoneNumbers:
      type: object
      properties:
        country_code:
          type: string
          example : "+261"
        number:
          type: string
          example: "0341126005"

    CreateStudent:
      type: object
      properties:
        name:
          type: string
          example: "Rakoto"
        birth_date:
          type: string
          format: date
          example: "2022-01-01"

    Student:
      allOf:
        - $ref: '#/components/schemas/CreateStudent'
        
      type: object
      properties:
        id:
          type: integer
          example: 10
        phoneNumbers: 
          type: array
          items:
            $ref:  '#/components/schemas/phoneNumbers'
          
    CreateCourse:
      type: object
      properties:
        code: 
          type: string
          example: "EL1P1"
        name:
          type: string
          example: "API DOCUMENTATION"
        Teacher: 
          type: string
          example: "Rabe"
        Created_Date:
          type: string
          format: date
    Course:
      properties:
        id:
          type: integer
          example: 10
      allOf:
      - $ref: '#/components/schemas/CreateCourse'